export const AREAS = {
  previdenciario: {
    id: 'previdenciario',
    nome: 'Previdenciário',
    icone: 'Shield',
    cor: '#e11d48',
    corBg: 'bg-rose-50',
    corTexto: 'text-rose-700',
    corBorda: 'border-rose-200',
    ativo: true,
    descricao: 'Aposentadoria, benefícios, auxílios e revisões',
    pecas: [
      'peticao_inicial', 'contestacao', 'replica', 'apelacao', 'agravo',
      'embargos', 'recurso_especial', 'tutela', 'cumprimento', 'contrarrazoes',
    ],
    modelos: [
      'procuracao', 'contrato_honorarios', 'substabelecimento', 'declaracao_hipossuficiencia',
    ],
    tipos_documento: [
      'cnis', 'indeferimento', 'cessacao', 'carta_concessao', 'laudo_medico',
      'ppp', 'ctps', 'procuracao', 'rg_cpf', 'comprovante_residencia', 'outro',
    ],
  },
  trabalhista: {
    id: 'trabalhista',
    nome: 'Trabalhista',
    icone: 'Briefcase',
    cor: '#D97706',
    corBg: 'bg-amber-50',
    corTexto: 'text-amber-700',
    corBorda: 'border-amber-200',
    ativo: true,
    descricao: 'Rescisão, horas extras, verbas trabalhistas e acordos',
    pecas: [
      'peticao_inicial', 'contestacao', 'replica', 'recurso_ordinario',
      'recurso_revista', 'agravo', 'embargos', 'tutela', 'cumprimento',
      'contrarrazoes', 'acordo',
    ],
    modelos: [
      'procuracao', 'contrato_honorarios', 'substabelecimento', 'notificacao_extrajudicial',
    ],
    tipos_documento: [
      'ctps', 'trct', 'holerites', 'contrato_trabalho', 'acordo_coletivo',
      'sentenca', 'acordao', 'ata_audiencia', 'procuracao', 'rg_cpf', 'outro',
    ],
  },
  civel: {
    id: 'civel',
    nome: 'Cível',
    icone: 'Scale',
    cor: '#059669',
    corBg: 'bg-emerald-50',
    corTexto: 'text-emerald-700',
    corBorda: 'border-emerald-200',
    ativo: false,
    descricao: 'Contratos, indenizações, cobranças e ações cíveis',
    pecas: [],
    modelos: [],
    tipos_documento: [],
  },
  criminal: {
    id: 'criminal',
    nome: 'Criminal',
    icone: 'Gavel',
    cor: '#DC2626',
    corBg: 'bg-red-50',
    corTexto: 'text-red-700',
    corBorda: 'border-red-200',
    ativo: false,
    descricao: 'Defesa criminal, habeas corpus e recursos penais',
    pecas: [],
    modelos: [],
    tipos_documento: [],
  },
  tributario: {
    id: 'tributario',
    nome: 'Tributário',
    icone: 'Receipt',
    cor: '#7C3AED',
    corBg: 'bg-violet-50',
    corTexto: 'text-violet-700',
    corBorda: 'border-violet-200',
    ativo: false,
    descricao: 'Impostos, parcelamentos e planejamento tributário',
    pecas: [],
    modelos: [],
    tipos_documento: [],
  },
  empresarial: {
    id: 'empresarial',
    nome: 'Empresarial',
    icone: 'Building2',
    cor: '#0891B2',
    corBg: 'bg-cyan-50',
    corTexto: 'text-cyan-700',
    corBorda: 'border-cyan-200',
    ativo: false,
    descricao: 'Contratos empresariais, societário e recuperação judicial',
    pecas: [],
    modelos: [],
    tipos_documento: [],
  },
} as const

export type AreaId = keyof typeof AREAS
export type Area = typeof AREAS[AreaId]
